backend/models/Canciones.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "canciones".
 *
 * @property integer $Id
 * @property integer $IdUsuario
 * @property string $Titulo
 * @property string $Audio
 * @property string $Letra
 * @property string $detalle
 * @property string $Fecha
 * @property string $Genero
 * @property integer $Megusta
 */
class Canciones extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public $Genero2;
    public $file;

    public static function tableName()
    {
        return 'canciones';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['IdUsuario', 'Titulo', 'Audio', 'Letra', 'detalle', 'Fecha', 'Genero', 'Megusta'], 'required'],
            [['IdUsuario', 'Megusta'], 'integer'],
            [['Letra'], 'string'],
            [['Fecha','Genero2'], 'safe'],
            [["file"], "file"],
            [['Titulo'], 'string', 'max' => 30],
            [['Audio'], 'string', 'max' => 120],
            [['detalle', 'Genero'], 'string', 'max' => 50],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'Id' => 'ID',
            'IdUsuario' => 'Id Usuario',
            'Titulo' => 'Titulo',
            'Audio' => 'Audio',
            'Letra' => 'Letra',
            'detalle' => 'Detalle',
            'Fecha' => 'Fecha',
            'Genero' => 'Genero',
            'Megusta' => 'Megusta',
        ];
    }
}

backend/controllers/CancionesController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Canciones;
use backend\models\Likes;
use backend\models\CancionesBuscar;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\Pagination;
use common\models\FormSearch;
use yii\helpers\Html;
use yii\web\UploadedFile;
/**
 * CancionesController implements the CRUD actions for Canciones model.
 */
class CancionesController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Canciones models.
     * @return mixed
     */
    public function actionIndex()
    {
        // $searchModel = new CancionesBuscar();
        // $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $form = new FormSearch;
                $search = null;
                $model=Canciones::find()->where(["IdUsuario"=>Yii::$app->user->Id])->all();
                if($form->load(Yii::$app->request->get()))
                {
                    if ($form->validate())
                    {
                        $search = Html::encode($form->q);

                        $model2=Canciones::find()
                        ->where(["like", "Titulo", $search])
                        ->orWhere(["like", "Letra", $search])
                        ->orWhere(["like", "detalle", $search]);
                        $count=Canciones::find()->where(["Titulo"=>$search])->count();
                         // $count2 = clone $model;
                                         $pages = new Pagination([
                                             "pageSize" => 12,
                                             "totalCount" => $count,
                                         ]);
                                         $model = $model2
                                                 ->offset($pages->offset)
                                                 ->limit($pages->limit)
                                                 ->all();
                    }
                    else
                    {
                        $form->getErrors();
                    }
                }
                else
                {
    
                    $table = Canciones::find()->where(["IdUsuario"=>Yii::$app->user->Id]);
                    $count = Canciones::find()->where(["IdUsuario"=>Yii::$app->user->Id])->count();
                    $pages = new Pagination([
                        "pageSize" => 12,
                        "totalCount" => $count,
                    ]);
                    $model = $table
                            ->offset($pages->offset)
                            ->limit($pages->limit)
                            ->all();
                }

   
        if ($count>0) {
            $mensaje=null;
        }else{
            $mensaje="no se necontraron registros";
        }
        return $this->render('index', [
            "model"=>$model,
            "mensaje"=>$mensaje,
            "pages"=>$pages,
            "form"=>$form,
            "search"=>$search,
            // 'searchModel' => $searchModel,
            // 'dataProvider' => $dataProvider,
        ]);
    }

    public function actionTodas()
    {
        // $searchModel = new CancionesBuscar();
        // $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $form = new FormSearch;
                $search = null;
                $model=Canciones::find()->all();
                if($form->load(Yii::$app->request->get()))
                {
                    if ($form->validate())
                    {
                        $search = Html::encode($form->q);

                        $model2=Canciones::find()
                        ->where(["like", "Titulo", $search])
                        ->orWhere(["like", "Letra", $search])
                        ->orWhere(["like", "detalle", $search]);
                        $count=Canciones::find()->where(["Titulo"=>$search])->count();
                         // $count2 = clone $model;
                                         $pages = new Pagination([
                                             "pageSize" => 12,
                                             "totalCount" => $count,
                                         ]);
                                         $model = $model2
                                                 ->offset($pages->offset)
                                                 ->limit($pages->limit)
                                                 ->all();
                    }
                    else
                    {
                        $form->getErrors();
                    }
                }
                else
                {
    
                    $table = Canciones::find();
                    $count = Canciones::find()->count();
                    $pages = new Pagination([
                        "pageSize" => 12,
                        "totalCount" => $count,
                    ]);
                    $model = $table
                            ->offset($pages->offset)
                            ->limit($pages->limit)
                            ->all();
                }

    
        if ($count>0) {
            $mensaje=null;
        }else{
            $mensaje="no se necontraron registros";
        }
        return $this->render('index', [
            "model"=>$model,
            "mensaje"=>$mensaje,
            "pages"=>$pages,
            "form"=>$form,
            "search"=>$search,
            // 'searchModel' => $searchModel,
            // 'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCanciones($id)
    {
        // $searchModel = new CancionesBuscar();
        // $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $form = new FormSearch;
                $search = null;
                $model=Canciones::find()->where(["IdUsuario"=>$id])->all();
                if($form->load(Yii::$app->request->get()))
                {
                    if ($form->validate())
                    {
                        $search = Html::encode($form->q);

                        $model2=Canciones::find()
                        ->where(["like", "Titulo", $search])
                        ->orWhere(["like", "Letra", $search])
                        ->orWhere(["like", "detalle", $search]);
                        $count=Canciones::find()->where(["Titulo"=>$search])->count();
                         // $count2 = clone $model;
                                         $pages = new Pagination([
                                             "pageSize" => 12,
                                             "totalCount" => $count,
                                         ]);
                                         $model = $model2
                                                 ->offset($pages->offset)
                                                 ->limit($pages->limit)
                                                 ->all();
                    }
                    else
                    {
                        $form->getErrors();
                    }
                }
                else
                {
    
                    $table = Canciones::find()->where(["IdUsuario"=>$id]);
                    $count = Canciones::find()->where(["IdUsuario"=>$id])->count();
                    $pages = new Pagination([
                        "pageSize" => 12,
                        "totalCount" => $count,
                    ]);
                    $model = $table
                            ->offset($pages->offset)
                            ->limit($pages->limit)
                            ->all();
                }

    
        if ($count>0) {
            $mensaje=null;
        }else{
            $mensaje="no se necontraron registros";
        }
        return $this->render('index', [
            "model"=>$model,
            "mensaje"=>$mensaje,
            "pages"=>$pages,
            "form"=>$form,
            "search"=>$search,
            // 'searchModel' => $searchModel,
            // 'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Canciones model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Canciones model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }

        $model = new Canciones();

        if ($model->load(Yii::$app->request->post())) {
            
            $model->file = UploadedFile::getInstance($model, 'file');
            if ($model->file!==Null) {
                # code...
                $model->file->name=str_replace(" ", "_",$model->file->name);
                $model->file->name=str_replace("Ñ", "n",$model->file->name);
                $model->file->name=str_replace("ñ", "n",$model->file->name);
                $model->file->name=str_replace("()", "",$model->file->name);
                $model->file->saveAs( 'images/mp3/'.$model->file->name.'.'.$model->file->extension);

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use backend\models\FormUpload;
use backend\models\Fotos;
use backend\models\Canciones;
use yii\web\UploadedFile;
use common\models\User;
/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index','admin','fotouplader','fotos','selectfoto','perfil','user','sample'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        $this->layout="loginLayout";
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(["site/admin"]);
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(["site/admin"]);
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    // Mis acciones personalizadas

    public function actionAdmin()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(["login"]);
        }
        // llamamos todo los datos
        $usuario=User::find()->where(["id"=>Yii::$app->user->Id])->one();
        return $this->render("admin",[
            "usuario"=>$usuario,
        ]);

    }

    public function actionFotouplader()
    {

        $fotos=new Fotos;
        $model = new FormUpload;
        $msg = null;

        if ($model->load(Yii::$app->request->post()))
        {
            $model->file = UploadedFile::getInstances($model, 'file');

            if ($model->file && $model->validate()) {
                foreach ($model->file as $file) {
                    $file->saveAs('images/perfil/' . $file->baseName . '.' . $file->extension);
                    $fotos->Titulo=$file->baseName;
                    $fotos->Url='/images/perfil/' . $file->baseName . '.' . $file->extension;
                    $fotos->Tipo=$file->extension;
                    $fotos->IdUsuario=Yii::$app->user->Id;


                    $msg = "<p><strong class='label label-info'>Enhorabuena, subida realizada con éxito</strong></p>";
                }
                    $fotos->save(false);
            }
        }
        return $this->render("upload", ["model" => $model, "msg" => $msg,"foto"=>$fotos->Url]);
    }

    public function actionFotos()
    {
        $fotos=Fotos::find()
            ->where(["IdUsuario"=>yii::$app->user->Id])
            ->all();
        return $this->render("fotos", [
            "model"=>$fotos
        ]);
    }
    public function actionSelectfoto($id)
    {
        $foto=Fotos::find()
            ->where(["Id"=>$id])
            ->one();
        $usuario=User::find()
            ->where(["id"=>yii::$app->user->Id])->one();

        $usuario->Foto=$foto->Url;
        if ($usuario->save(false)) {
            return $this->redirect(["site/admin"]);
        }else{
            return $this->redirect(["site/fotos"]);
        }
    }

    public function actionPerfil($id)
    {
        $perfil=User::find()
            ->where(["id"=>$id])
            ->one();
        return $this->render("perfil",[
            "perfil"=>$perfil
        ]);
    }

    public function actionUser()
    {
        // verificamos que este login
        if (Yii::$app->user->isGuest) {
            return $this->redirect(["site/login"]);
        }
        // buscamos todo los usuarios registrados
        $model=User::find()->all();
        return $this->render("user",[
            "model"=>$model,
        ]);
    }

   public function actionSample()
   {
   if (Yii::$app->request->isAjax) {
       $data = Yii::$app->request->post();
       $dataId= explode(":", $data['id']);
       \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
       // $dataId=(int)$dataId;
       $cancion=Canciones::findOne($dataId);
        // ->where(["Id"=>$dataId])
        // ->one();
       
        $g=$cancion["Titulo"];
       return [
           'dataId' => $g,
       ];
     }
   }
}

backend/views/canciones/_canciones.php
<?php 
    use yii\helpers\Html;
    use yii\helpers\Url;
    use common\models\User;

?>
<div class="ui four cards">
    <?php foreach ($model as $key): ?>
        <!-- buscamod informcaion de ususario dependiendo de cada cancion -->
        <?php
            $usuario=User::find()
                ->where(["id"=>$key->IdUsuario])
                ->one();
        ?>
        <div class="card">
            <div class="content">
                <a href="<?= Url::to(["site/perfil","id"=>$usuario->id]); ?>" class="ui mini right floated basic image label"><img src="<?= yii::getAlias("@recursos");?><?= $usuario->Foto; ?>">
                    <?= $usuario->username;?>
                </a>
                
                <!-- <img class="ui right floated mini ui image" src="https://www.socialtools.me/blog/wp-content/uploads/2016/04/foto-de-perfil.jpg"> -->
                <?php if ($key->Fecha==date("Y-m-d")): ?>
                    
                <a class="ui mini right floated blue tag label">Nuevo</a>
                <?php endif ?>
                
                <div class="header">
                    <?= $key->Titulo; ?>
                </div>

                <div class="meta">
                    <?= $key->Genero; ?>
                </div>
                <div class="description">
                    <?= $key->detalle; ?>
                </div>
            </div>
            <div class="extra content">
                <div class="ui tree buttons">
                    <a href="<?= Url::to(["canciones/view","id"=>$key->Id]); ?>" class="ui basic blue button">Ver</a>
                    <a href="<?= Url::to(["canciones/update","id"=>$key->Id]); ?>" class="ui basic green button">Editar</a>
                    <a href="<?= Url::to(["canciones/delete"]); ?>" class="ui basic red button">Eliminar</a>
                </div>
            </div>
        </div>
    <?php endforeach ?>
</div>

backend/views/canciones/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
// use \Zelenin\yii\SemanticUI\widgets\ActiveForm;
use dosamigos\ckeditor\CKEditor;
/* @var $this yii\web\View */
/* @var $model backend\models\Canciones */
/* @var $form yii\widgets\ActiveForm */
?>


<div class="canciones-form">

    <?php $form = ActiveForm::begin([
     // "method" => "post",
     // "enableClientValidation" => true,
     "options" => ["enctype" => "multipart/form-data"],
     ]); ?>

    <?= $form->field($model, 'IdUsuario',[
        'inputOptions'=>[
            "hidden"=>"true",
            "value"=>Yii::$app->user->Id
        ],
    ])->textInput()->label(false) ?>

    <?= $form->field($model, 'Titulo')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'file')->fileInput() ?>

    <!-- <?= $form->field($model, 'Letra')->textarea(['rows' => 6]) ?> -->
    
    <?= $form->field($model, 'Letra')->widget(CKEditor::className(), [
        'options' => ['rows' => 6],
        'preset' => 'basic',
    ]) ?>

    <?= $form->field($model, 'detalle')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Fecha')->textInput(["value"=>date("Y-m-d")]) ?>

    <?= $form->field($model, 'Genero')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Megusta')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/canciones/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\CancionesBuscar */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="canciones-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'Id') ?>

    <?= $form->field($model, 'IdUsuario') ?>

    <?= $form->field($model, 'Titulo') ?>

    <?= $form->field($model, 'Audio') ?>

    <?= $form->field($model, 'Letra') ?>

    <?php // echo $form->field($model, 'detalle') ?>

    <?php // echo $form->field($model, 'Fecha') ?>

    <?php // echo $form->field($model, 'Genero') ?>

    <?php // echo $form->field($model, 'Megusta') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/canciones/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\Canciones */

$this->title = 'Create Canciones';
$this->params['breadcrumbs'][] = ['label' => 'Canciones', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="canciones-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/canciones/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\data\Pagination;
use yii\widgets\LinkPager;
use yii\widgets\ActiveForm;
/* @var $this yii\web\View */
/* @var $searchModel backend\models\CancionesBuscar */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Canciones';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="canciones-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
<center>
    <a href="<?= Url::to(["canciones/create"]); ?>" class="btn btn-primary">Agregar Canciones</a>
</center>

<?php $f = ActiveForm::begin([
    "method" => "get",
    "action" => Url::toRoute("canciones/index"),
    "enableClientValidation" => true,
]);
?>

<div class="form-group">
    <?= $f->field($form, "q")->input("search") ?>
</div>

<?= Html::submitButton("Buscar", ["class" => "btn btn-primary"]) ?>

<?php $f->end() ?>

<h3><?= $search ?></h3>


    <hr>
    <?= $mensaje; ?>
    <?=  $this->render("_canciones",[
        "model"=>$model,
    ]); ?>

</div>

<?= LinkPager::widget([
    "pagination" => $pages,
]); ?>

backend/views/canciones/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Canciones */

$this->title =$model->Titulo;
$this->params['breadcrumbs'][] = ['label' => 'Canciones', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->Titulo, 'url' => ['view', 'id' => $model->Id]];
$this->params['breadcrumbs'][] = 'Actualizar';
?>
<div class="canciones-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/canciones/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\Canciones */

$this->title = $model->Titulo;
$this->params['breadcrumbs'][] = ['label' => 'Canciones', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="canciones-view">

    <!-- <h1><?= Html::encode($this->title) ?></h1> -->

    <p>
        <?php // Html::a('Update', ['update', 'id' => $model->Id], ['class' => 'btn btn-primary']) ?>
        <?php /* Html::a('Delete', ['delete', 'id' => $model->Id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
            ]) */?>
        </p>

        <div class="ui small  icon buttons flotante2">
          <button data-tooltip="Reproducir musica" id="boton" class="ui button">
            <i id="pause" class="play icon"></i>
        </button>
        

        <a href="<?= Url::to(["canciones/update","id"=>$model->Id]); ?>">
            <button data-tooltip="Editar Cancion" class="ui button"> <i class="edit icon"></i>
            </button>
        </a>

        <?=  Html::a('
            <button data-tooltip="Eliminar" data-position="top right" class="ui button">
                <i class="delete icon"></i>
            </button>
            ', ['delete', 'id' => $model->Id], [
            'data' => [
            'confirm' => 'Deseas eliminar esta cancion?',
            'method' => 'post',
            ],
            ]) ?>

      <!-- <button class="ui button"><i class="upload icon"></i></button>
      <button class="ui button"><i class="download icon"></i></button> -->
  </div>
  <?php if (file_exists(yii::getAlias("@frontend")."/web/images/mp3/".$model->Audio)): ?>
    <audio id="reproductor" class="flotante col-md-9" src="<?= yii::getAlias("@recursos");?>/images/mp3/<?= $model->Audio; ?>" controls type="audio/mp3"></audio>
  <?php endif ?>

  <?php if (file_exists(yii::getAlias("@backend")."/web/images/mp3/".$model->Audio)): ?>
      <audio id="reproductor" class="flotante col-md-9" src="<?= yii::getAlias("@recursosb");?>/images/mp3/<?= $model->Audio; ?>" controls type="audio/mp3"></audio>
  <?php endif ?>

    <div class="panel panel-default">
      <div class="panel-body">
        <div class="ui items">
      <div class="item">
        <div class="content">
          <!-- botones de favoritos -->
          <div class="extra content">
            <span class="left floated">
              <div class="ui labeled button" tabindex="0">
                <?php if (backend\models\Likes::find()->where(["Id_Caciones"=>$model->Id])->andWhere(["Id_Usuario"=>Yii::$app->user->Id])->count()>0): ?>
                  
                <div id="like" class="ui button i"><i class="heart icon"></i> Me gusta </div>
                <a class="ui basic label">
                  <?= backend\models\Likes::find()->where(["Id_Caciones"=>$model->Id])->count();?>
                </a>
                <?php endif ?>
                <?php if (backend\models\Likes::find()->where(["Id_Caciones"=>$model->Id])->andWhere(["Id_Usuario"=>Yii::$app->user->Id])->count()==0): ?>
                  
                <div class="ui button i"><i class="heart icon"></i> No Me Gusta </div>
                <a class="ui basic label">
                  <?= backend\models\Likes::find()->where(["Id_Caciones"=>$model->Id])->count();?>
                </a>
                <?php endif ?>
              </div>
            </span>

            <span class="right floated star"><i class="user icon"></i>Autor:
                <?php $autor=\common\models\User::find()
                ->where(["id"=>$model->IdUsuario])
                ->one();
                echo $autor->username;
                ?>
            </span>
        </div>
        <!-- finde  botones de favorito -->
        <a class="header">
          <?= $model->Titulo; ?>
      </a>
      <div class="text-center description">
        <p>
            <?= $model->Letra;?>
        </p>
    </div>
    <div class="extra"><i class="green check icon"></i>
      <?= $model->Megusta;?>
    </div>
</div>
</div>
</div>
<div class="id" style="display:none;">
  <?= $model->Id; ?>
</div>




<?php
$this->registerJs("
$(function(){

      $('.ui.button.i').on('click', function(){
        var urlp='".yii\helpers\Url::to(['canciones/megusta'])."';
        $.ajax({
            url: urlp,
           type: 'POST',
           data: {id: $('.id').text()},
           success: function (data) {
              if(data==true){
                $('#like').html('Megusta');
              }if(data==false){
                $('#like').html('No Megusta');
              }
           }

      });
      });

});
");
?>

      </div>
    </div>
    

</div>