backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use backend\models\FormUpload;
use backend\models\Fotos;
use backend\models\Canciones;
use yii\web\UploadedFile;
use common\models\User;
/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index','admin','fotouplader','fotos','selectfoto','perfil','user','sample'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        $this->layout="loginLayout";
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(["site/admin"]);
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(["site/admin"]);
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    // Mis acciones personalizadas

    public function actionAdmin()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(["login"]);
        }
        // llamamos todo los datos
        $usuario=User::find()->where(["id"=>Yii::$app->user->Id])->one();
        return $this->render("admin",[
            "usuario"=>$usuario,
        ]);

    }

    public function actionFotouplader()
    {

        $fotos=new Fotos;
        $model = new FormUpload;
        $msg = null;

        if ($model->load(Yii::$app->request->post()))
        {
            $model->file = UploadedFile::getInstances($model, 'file');

            if ($model->file && $model->validate()) {
                foreach ($model->file as $file) {
                    $file->saveAs('images/perfil/' . $file->baseName . '.' . $file->extension);
                    $fotos->Titulo=$file->baseName;
                    $fotos->Url='/images/perfil/' . $file->baseName . '.' . $file->extension;
                    $fotos->Tipo=$file->extension;
                    $fotos->IdUsuario=Yii::$app->user->Id;


                    $msg = "<p><strong class='label label-info'>Enhorabuena, subida realizada con éxito</strong></p>";
                }
                    $fotos->save(false);
            }
        }
        return $this->render("upload", ["model" => $model, "msg" => $msg,"foto"=>$fotos->Url]);
    }

    public function actionFotos()
    {
        $fotos=Fotos::find()
            ->where(["IdUsuario"=>yii::$app->user->Id])
            ->all();
        return $this->render("fotos", [
            "model"=>$fotos
        ]);
    }
    public function actionSelectfoto($id)
    {
        $foto=Fotos::find()
            ->where(["Id"=>$id])
            ->one();
        $usuario=User::find()
            ->where(["id"=>yii::$app->user->Id])->one();

        $usuario->Foto=$foto->Url;
        if ($usuario->save(false)) {
            return $this->redirect(["site/admin"]);
        }else{
            return $this->redirect(["site/fotos"]);
        }
    }

    public function actionPerfil($id)
    {
        $perfil=User::find()
            ->where(["id"=>$id])
            ->one();
        return $this->render("perfil",[
            "perfil"=>$perfil
        ]);
    }

    public function actionUser()
    {
        // verificamos que este login
        if (Yii::$app->user->isGuest) {
            return $this->redirect(["site/login"]);
        }
        // buscamos todo los usuarios registrados
        $model=User::find()->all();
        return $this->render("user",[
            "model"=>$model,
        ]);
    }

   public function actionSample()
   {
   if (Yii::$app->request->isAjax) {
       $data = Yii::$app->request->post();
       $dataId= explode(":", $data['id']);
       \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
       // $dataId=(int)$dataId;
       $cancion=Canciones::findOne($dataId);
        // ->where(["Id"=>$dataId])
        // ->one();
       
        $g=$cancion["Titulo"];
       return [
           'dataId' => $g,
       ];
     }
   }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use common\models\User;
use frontend\models\PasswordResetRequestForm;
use frontend\models\Fotos;
use frontend\models\FormUpload;
use frontend\models\Configuracion;
use frontend\models\Genero;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use backend\models\Canciones;
use yii\web\UploadedFile;
/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'auth' => [
                        'class' => 'yii\authclient\AuthAction',
                        'successCallback' => [$this, "successCallback"],
                    ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $this->layout="main2";
        return $this->render('index');
    }

    public function successCallback($client)
    {
        $attributes = $client->getUserAttributes();
            // user login or signup comes here
            /*
            Checking facebook email registered yet?
            Maxsure your registered email when login same with facebook email
            die(print_r($attributes));
            */
            
            $user = \common\modules\auth\models\User::find()->where(["email"=>$attributes["email"]])->one();
            if(!empty($user)){
                Yii::$app->user->login($user);
            
            }else{
                // Save session attribute user from FB
                $session = Yii::$app->session;
                $session["attributes"]=$attributes;
                // redirect to form signup, variabel global set to successUrl
                $this->successUrl = \yii\helpers\Url::to(["signup"]);
            }
    }
    public $successUrl = 'Success';

    public function actionIntro()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(["login"]);
        }
        // llamamos todo los datos
        $usuario=User::find()->where(["id"=>Yii::$app->user->Id])->one();
        return $this->render("intro",[
            "usuario"=>$usuario,
        ]);
    }

     public function actionFotouplader()
     {

         $fotos=new Fotos;
         $model = new FormUpload;
         $msg = null;

         if ($model->load(Yii::$app->request->post()))
         {
             $model->file = UploadedFile::getInstances($model, 'file');

             if ($model->file && $model->validate()) {
                 foreach ($model->file as $file) {
                     $file->saveAs('images/perfil/' . $file->baseName . '.' . $file->extension);
                     $fotos->Titulo=$file->baseName;
                     $fotos->Url='/images/perfil/' . $file->baseName . '.' . $file->extension;
                     $fotos->Tipo=$file->extension;
                     $fotos->IdUsuario=Yii::$app->user->Id;


                     $msg = "<p><strong class='label label-info'>Enhorabuena, subida realizada con éxito</strong></p>";
                 }
                     $fotos->save(false);
             }
         }
         return $this->render("upload", ["model" => $model, "msg" => $msg,"foto"=>$fotos->Url]);
     }

     public function actionFotos()
     {
         $fotos=Fotos::find()
             ->where(["IdUsuario"=>yii::$app->user->Id])
             ->all();
         return $this->render("fotos", [
             "model"=>$fotos
         ]);
     }
     public function actionDeletefoto($id)
     {
        $foto=Fotos::find()
            ->where(["Id"=>$id,"IdUsuario"=>yii::$app->user->Id])
            ->one();

                if (file_exists(yii::getAlias("@frontend")."/web/".$foto->Url)){
                    if (unlink(yii::getAlias("@frontend")."/web/".$foto->Url)) {
                        $foto->delete();
                        $usuario=User::find()
                            ->where(["id"=>yii::$app->user->Id])->one();
                            $usuario->Foto=Null;
                            $usuario->save(false);

                        return $this->redirect(["site/fotos"]);
                    }
                }else{
            
                if (file_exists(yii::getAlias("@backend")."/web/".$foto->Url)){
                    if (unlink(yii::getAlias("@backend")."/web/".$foto->Url)) {
                        $foto->delete();

                        $usuario=User::find()
                            ->where(["id"=>yii::$app->user->Id])->one();
                            $usuario->Foto=Null;
                            $usuario->save(false);

                        return $this->redirect(["site/fotos"]);
                    }
                    
                }
            }
            var_dump($foto);
        
     }
     public function actionSelectfoto($id)
     {
         $foto=Fotos::find()
             ->where(["Id"=>$id])
             ->one();
         $usuario=User::find()
             ->where(["id"=>yii::$app->user->Id])->one();

         $usuario->Foto=$foto->Url;
         if ($usuario->save(false)) {
             return $this->redirect(["site/intro"]);
         }else{
             return $this->redirect(["site/fotos"]);
         }
     }

     public function actionPerfil($id)
     {
         $perfil=User::find()
             ->where(["id"=>$id])
             ->one();
         return $this->render("perfil",[
             "perfil"=>$perfil
         ]);
     }

     public function actionUser()
     {
         // verificamos que este login
         if (Yii::$app->user->isGuest) {
             return $this->redirect(["site/login"]);
         }
         // buscamos todo los usuarios registrados
         $model=User::find()->all();
         return $this->render("user",[
             "model"=>$model,
         ]);
     }

    public function actionSample()
    {
    if (Yii::$app->request->isAjax) {
        $data = Yii::$app->request->post();
        $dataId= explode(":", $data['id']);
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        // $dataId=(int)$dataId;
        $cancion=Canciones::findOne($dataId);
         // ->where(["Id"=>$dataId])
         // ->one();
        
         $g=$cancion["Titulo"];
        return [
            'dataId' => $g,
        ];
      }
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        $this->layout="loginLayout";
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            $foto=User::find()->where(["id"=>yii::$app->user->Id])->one()->Foto;
            if ($foto=="") {
                Yii::$app->session->setFlash('mensaje',"Bienvenido a Tarriworld.com te invitamos a que ingreses una foto de perfil.");
            }
            
            return $this->redirect(["canciones/index"]);
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }


    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionPolitica()
    {
        return $this->render('politica');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $this->layout="main2";
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                  $configuracion=new Configuracion();
                  $configuracion->Id_Usuario=Yii::$app->user->Id;

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/fotos.php
<?php 
use yii\helpers\Url;
?>
<hr>
<center><a data-tooltip="Subir fotos" href="<?= Url::to(["site/fotouplader"]); ?>">
	<button class="circular ui  icon button">
			<i class="icon upload"></i>
	
		</button>
	</a></center>	
<hr>

	<div class="ui four stackable cards">
	<?php foreach ($model as $key): ?>
	  <div class="card">
	    <div class="image">
		      <a href="<?= Url::to(["site/selectfoto","id"=>$key->Id]); ?>" class="ui left corner label">
					<i class="checkmark box icon"></i>
				</a> 

				<a href="<?= Url::to(["site/selectfoto","id"=>$key->Id]); ?>" class="ui right corner label">
					<i class="delete icon"></i>
				</a>  
				<img src="<?= yii::getAlias("@recursos");?><?= $key->Url; ?>">
	    </div>
	  </div>

    <div class="extra">

    </div>
		  
		  
	<?php endforeach ?>
		</div>

frontend/views/site/index.php
<?php
use yii\helpers\Url;

/* @var $this yii\web\View */

$this->title = 'TarriWorld';
?>
<div class="site-index">
    <div class="jumbotron">
      <!-- <img width="80%" src="<?= yii::getAlias("@recursos");?>/images/Tarriword.png" alt=""> -->
      <img width="80%" src="<?= yii::getAlias("@recursos");?>/images/TarriworldG.png" alt="">
<!-- <img src="<?= yii::getAlias("@recursos");?>/images/logo.jpg" alt=""> -->

        <p class="lead">
            El Mundo Creativo Espera Por Ti<br>
            <small>Imagina, Crea, Y Piensa en Grande.</small>
        </p>

        <p><a class="btn btn-lg btn-block btn-primary" href="<?= Url::to(["site/login"]);?>">Iniciar</a></p>
    </div>

   <!-- Three columns of text below the carousel -->
        <div class="row">
          <div class="col-lg-4">
            <img class="img-circle" src="<?= yii::getAlias("@recursos");?>/images/Tarriword.png" alt="Generic placeholder image" width="140" height="140">
            <h2>Heading</h2>
            <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
            <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
            <h2>Heading</h2>
            <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
            <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
            <h2>Heading</h2>
            <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
            <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
          </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->
</div>

frontend/views/site/intro.php
<?php 
use backend\models\Canciones;
use common\models\User;
use yii\helpers\Url;
?>
<div class="col-sm-4 col-md-3 col-lg-3">
	<!-- Tejetas de perfil -->
	<div class="ui card">
		<div class="image">
			<img src="<?= yii::getAlias("@recursos");?><?= $usuario->Foto; ?>">
		</div>
		<div class="content">
			<a class="header">
				<?= $usuario->username;?>
			</a>
			<div class="meta">
				<span class="date">
					<?= $usuario->email;?>
				</span>
			</div>
			<div class="description">
				<a href="<?= Url::to(["canciones/create"]); ?>">
					<button data-tooltip="Subir Canciones" data-position="top left" class="circular ui icon button">
						<i class="icon upload"></i>

					</button>
				</a>
				<a href="<?= Url::to(["site/fotos"]); ?>">
					<button data-tooltip="Seleccionar Foto De Perfil" data-position="top left" class="circular ui icon button">
						<i class="icon picture"></i>

					</button>
				</a>
			</div>
		</div>
		<div class="extra content">
			<a href="<?= Url::to(["canciones/index"]); ?>" data-tooltip="Mis Canciones"><i class="music icon"></i>
				<?= $countC=Canciones::find()->where(["IdUsuario"=>Yii::$app->user->Id])->count(); ?>
			</a>
		</div>
	</div>
</div>
<!-- actividades -->
<div class="col-sm-8 col-md-9 col-lg-9">
	<div class="panel panel-default">
		<div class="panel-body">
			<!-- cuerpo del panel principal -->
			<div class="ui four statistics">
				<!-- Total de canciones creadas -->
				<div class="statistic">
					<div class="value" data-tooltip="" data-position="bottom center"><i class="music icon"></i>
						<?= Canciones::find()->where(["IdUsuario"=>Yii::$app->user->Id])->count(); ?>
					</div>
					<div class="label">Mis Canciones</div>
				</div>
				<!-- Total de usuarios Registrados -->
				<div class="statistic">
					<div class="value" data-tooltip="" data-position="bottom center"><i class="checked calendar icon"></i>
						<?= User::find()->count(); ?>
					</div>
					<div class="label">Por Terminar</div>
				</div>
				<!-- Total de usuarios Inactivos -->
				<div class="statistic">
					<div class="value" data-tooltip="" data-position="bottom center"><i class="world icon"></i>
						<?= Canciones::find()->where(["Permiso"=>"1"])->count(); ?>
					</div>
					<div class="label">Canciones Publicas</div>
				</div>
								<!-- Total de usuarios Inactivos -->
				<div class="statistic">
					<div class="value" data-tooltip="" data-position="bottom center"><i class="line chart icon"></i>
						<?= User::find()->where(["status"=>"0"])->count(); ?>
					</div>
					<div class="label">Visitas</div>
				</div>
			</div>
			<div class="ui horizontal divider header"><i class="newspaper icon"></i>Ultimas 3 Canciones Creadas</div>
			<!-- buscamos todas las canciones registradas -->
			<?php $ultimasC=Canciones::find()
			->orderBy('Fecha DESC')
			->limit(3)
			->all(); ?>
			<div style="padding-left:4%;" class="ui three column grid">
				<div class="row">
					<?php foreach ($ultimasC as $key): ?>
						<!-- buscamos los usuarios de cada cancion -->
						<?php $usuarios=User::find()
						->where(["id"=>$key->IdUsuario])
						->One();
						?>
						<div class="column">
							<div class="ui card">
								<div class="content">
									<div class="header">
										<?= $key->Titulo; ?>
									</div>
									<div class="meta">
										<span class="right floated time">
											<?= $key->Fecha; ?>
										</span>
										<span class="category">
											<?= $key->Genero; ?>
										</span>
									</div>
									<div class="description">
										<p>
											<?= $key->detalle; ?>
										</p>
									</div>
								</div>
								<div class="extra content">
									<div class="right floated author">
										<img class="ui avatar image" src="<?= yii::getAlias("@recursos");?><?= $usuarios->Foto; ?>">
										<?= $usuarios->username ?>
									</div>
								</div>
							</div>
						</div>
					<?php endforeach ?>
				</div>
					<a href="<?= Url::to(["canciones/todas"]); ?>">
						<div class="ui right floated primary button">Mostrar Todas las Canciones<i class="right chevron icon"></i>
						</div>
					</a>
				</div>
		</div>

	</div>
</div>
</div>

frontend/views/site/login.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
?>

<center><img width="50%" src="<?= yii::getAlias("@recursos");?>/images/TarriworldG.png" alt=""></center>
<br>
<br>
<br>
<div class="site-login">

    <div  class="panel panel-default col-md-4 col-md-offset-4">
   <div class="panel-body">
    <?= Html::a("
        <span class=\"glyphicon glyphicon-chevron-left\" aria-hidden=\"true\"></span>
    ",["site/index"]);?>
    <div class="ui horizontal divider header"><i class="user icon"></i>Iniciar Seccion</div>

     <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

     <?= $form->field($model, 'username',[
        'inputOptions' => [
            'placeholder' => $model->getAttributeLabel('Usuario'),
            'autofocus' => true
        ],
                    // 'inputTemplate' => '<div class="input-group"><span class="input-group-addon">@</span>{input}</div>',

        ])->textInput()->label(false) ?>

        <?= $form->field($model, 'password')->passwordInput(["placeholder"=>"Password",'autofocus' => true])->label(false) ?>

        <?= $form->field($model, 'rememberMe')->checkbox()->label("Recordarme la cuenta") ?>

        <div class="form-group">
            <?= Html::submitButton('Iniciar', ['class' => 'btn btn-primary btn-block', 'name' => 'login-button']) ?>
            <?= Html::a('Reiniciar', ['site/request-password-reset']) ?>
        </div>

        <?php ActiveForm::end(); ?>

    </div>
</div>

</div>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/user.php
<?php 
use yii\helpers\Html;
use yii\helpers\Url;
?>
<div class="ui four column grid">
<?php foreach ($model as $key): ?>
  <div class="column">
    <div class="ui fluid card">
      <div class="image">
        <img src="<?= yii::getAlias("@recursos");?><?= $key->Foto;?>">
      </div>
      <div class="content">
        <a href="<?= Url::to(["site/perfil","id"=>$key->id]);?>" class="header"><?= $key->username; ?></a>
      </div>
    </div>
  </div>
<?php endforeach ?>
</div>